name: CI/CD - Backend Despachos

on:
  push:
    branches:
      - deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Springboot-API-REST-DESPACHO
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Login a Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build y Push imagen a ECR
        run: |
          docker build -t innovatech-despachos .
          docker tag innovatech-despachos:latest 199400803677.dkr.ecr.us-east-1.amazonaws.com/innovatech-despachos:latest
          docker push 199400803677.dkr.ecr.us-east-1.amazonaws.com/innovatech-despachos:latest

      - name: Actualizar kubeconfig
        run: |
          aws eks update-kubeconfig --region us-east-1 --name Cluster_EKS

      - name: Deploy a EKS
        run: |
          kubectl set image deployment/despachos-deployment despachos=199400803677.dkr.ecr.us-east-1.amazonaws.com/innovatech-despachos:latest
          kubectl rollout status deployment/despachos-deployment